### PR TITLE
Added blog posts for AAAAAAA and Baby-Shark UTCTF 2022

### PR DESCRIPTION
**Pull request by frehlid**
Added write ups for the beginner challenged AAAAAAAA and Baby Shark from UTCTF 2022.

### CODE REVIEW

**Comment by nneonneo** [comment]
You'll want to make an author page in [/_authors](https://github.com/ubcctf/ubcctf.github.io/tree/master/_authors) in order to link your username to the right members page.

**Comment by frehlid** [comment]
Page added, thank you!

**Comment by jamiepoli** [comment]
The author field in your blog should correspond to your `short_name` defined in your authors page, instead of your regular name

**Comment by jamiepoli** [comment]
Additionally, do you have these parameters in your authors page? 
`position`
`website`
`website_title`

Please consult the pinned messages in the UTCTF channel - theres a guide there to help you with what you need for your PR.

**Comment by frehlid** [comment]
Ah, thank you! I left the parameters out because I wasn't sure what to put. I've filled them in now, and corrected the short-name.

**Pull request merged**
